/**
 * ====================================================================================
 *
 *                                奇美拉协议 · 产物
 *                      Project: pollinations-2api (Cloudflare Worker)
 *                                Version: 1.0.2 (Fixed)
 *                            Generated by: Chief AI Executive
 *
 * ====================================================================================
 *
 *  部署指南:
 *  1. 登录 Cloudflare Dashboard。
 *  2. 进入 "Workers & Pages" -> "Create application" -> "Create Worker"。
 *  3. 为你的 Worker 命名，然后点击 "Deploy"。
 *  4. 点击 "Edit code"，将本文件的全部内容粘贴到编辑器中。
 *  5. 点击 "Save and deploy"。
 *  6. (可选) 配置自定义域名。
 *  7. 访问你的 Worker 域名，即可看到“开发者驾驶舱”UI。
 *
 * ====================================================================================
 */


// ====================================================================================
// 第一部分：后端逻辑 (Backend Logic)
// ====================================================================================

/**
 * [架构核心] 配置即代码 (Configuration-as-Code)
 * 所有关键参数在此定义，便于维护和审查。
 */
const CONFIG = {
  // --- 项目元数据 ---
  PROJECT_NAME: "pollinations-2api",
  PROJECT_VERSION: "1.0.2",
  // --- 安全配置 ---
  API_MASTER_KEY: "1"， // 遵循指令，设置为 "1"
  // --- 上游服务配置 ---
  UPSTREAM_URL: "https://text.pollinations.ai",
  // --- 模型配置 ---
  DEFAULT_MODEL: "pollinations-default",
  KNOWN_MODELS: ["pollinations-default"]，
  // --- 伪流式生成配置 ---
  PSEUDO_STREAM_CHUNK_DELAY: 25， // 模拟打字机效果的延迟（毫秒）
};

/**
 * [Worker入口] 主 fetch 事件处理器
 * 作为请求的路由器，将流量分发到 UI 处理器或 API 处理器。
 */
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 路由分发
    try {
      switch (url.pathname) {
        case "/":
          if (request。method === "GET") {
            // [修复] handleUIPage 不需要 request 参数，已移除
            return handleUIPage();
          }
          break;
        case "/v1/chat/completions":
          if (request.method === "POST") {
            return handleApiRequest(request);
          }
          break;
        case "/v1/models":
           if (request.method === "GET") {
            return handleModelsRequest(request);
          }
          break;
      }
      // 对于所有其他路径或不匹配的方法，返回 404
      return new Response(
        JSON.stringify({
          error: {
            message: `路径 ${request.method} ${url.pathname} 未找到。请访问根路径'/'获取使用指南。`,
            type: "invalid_request_error",
            code: "not_found"
          }
        }), {
          status: 404,
          headers: { 'Content-Type': 'application/json' }
        }
      );
    } catch (err) {
      console.error(`[FATAL] Unhandled exception in fetch handler: ${err.stack}`);
      return new Response(JSON.stringify({
        error: {
          message: `服务器内部发生严重错误: ${err.message}`,
          type: "internal_server_error"
        }
      }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      });
    }
  },
};

/**
 * [API处理器] 处理 /v1/chat/completions 请求
 * @param {Request} request - 传入的请求对象
 */
async function handleApiRequest(request) {
  // 1. 认证
  const authHeader = request.headers.get("Authorization");
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return new Response(JSON.stringify({ error: { message: "需要提供 Bearer Token 认证。", type: "authentication_error" } }), { status: 401, headers: { 'Content-Type': 'application/json' } });
  }
  const token = authHeader.substring(7);
  if (token !== CONFIG.API_MASTER_KEY) {
    return new Response(JSON.stringify({ error: { message: "无效的 API Key。", type: "authentication_error" } }), { status: 403, headers: { 'Content-Type': 'application/json' } });
  }

  // 2. 请求体解析与验证
  let requestData;
  try {
    requestData = await request.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: { message: "无效的JSON请求体。", type: "invalid_request_error" } }), { status: 400, headers: { 'Content-Type': 'application/json' } });
  }

  const messages = requestData.messages;
  if (!messages || !Array.isArray(messages) || messages.length === 0) {
    return new Response(JSON.stringify({ error: { message: "请求体中缺少 'messages' 字段或其为空。", type: "invalid_request_error" } }), { status: 400, headers: { 'Content-Type': 'application/json' } });
  }

  const lastUserMessage = messages.filter(m => m.role === 'user').pop();
  if (!lastUserMessage || !lastUserMessage.content) {
    return new Response(JSON.stringify({ error: { message: "在 'messages' 中未找到有效的用户消息。", type: "invalid_request_error" } }), { status: 400, headers: { 'Content-Type': 'application/json' } });
  }
  const prompt = lastUserMessage.content;

  // 3. 请求水印与追踪
  const requestId = `chatcmpl-${crypto.randomUUID()}`;

  try {
    // 4. 构造并执行上游请求
    const upstreamUrl = `${CONFIG.UPSTREAM_URL}/${encodeURIComponent(prompt)}`;
    const upstreamResponse = await fetch(upstreamUrl, {
      method: "GET",
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://chatbot.rizqioliveira.my.id/",
        "Origin": "https://chatbot.rizqioliveira.my.id",
      },
      // 暗示 Cloudflare 优先使用 HTTP/3
      cf: {
        http3: 'on'
      }
    });

    if (!upstreamResponse.ok) {
      const errorText = await upstreamResponse.text();
      throw new Error(`上游服务错误 (状态码: ${upstreamResponse.status}): ${errorText}`);
    }

    const responseText = await upstreamResponse.text();

    // 5. 应用【模式：伪流式生成】
    const stream = streamTextAsSse(responseText, requestId, CONFIG.DEFAULT_MODEL);

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream; charset=utf-8",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        "X-Worker-Trace-ID": requestId,
      },
    });

  } catch (err) {
    console.error(`[API_ERROR] Request ID ${requestId}: ${err.stack}`);
    return new Response(JSON.stringify({
      error: {
        message: `处理请求时发生错误: ${err.message}`,
        type: "api_error",
        request_id: requestId
      }
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json', "X-Worker-Trace-ID": requestId }
    });
  }
}

/**
 * [API处理器] 处理 /v1/models 请求
 * @param {Request} request - 传入的请求对象
 */
async function handleModelsRequest(request) {
    // 认证
    const authHeader = request.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
        return new Response(JSON.stringify({ error: { message: "需要提供 Bearer Token 认证。", type: "authentication_error" } }), { status: 401, headers: { 'Content-Type': 'application/json' } });
    }
    const token = authHeader.substring(7);
    if (token !== CONFIG.API_MASTER_KEY) {
        return new Response(JSON.stringify({ error: { message: "无效的 API Key。", type: "authentication_error" } }), { status: 403, headers: { 'Content-Type': 'application/json' } });
    }

    const modelData = {
        object: "list",
        data: CONFIG.KNOWN_MODELS.map(modelId => ({
            id: modelId,
            object: "model",
            created: Math.floor(Date.now() / 1000),
            owned_by: "lzA6"
        }))
    };

    return new Response(JSON.stringify(modelData), {
        headers: {
            'Content-Type': 'application/json',
            'Cache-Control': 'public, max-age=3600' // 模型列表可缓存1小时
        }
    });
}


/**
 * [工具函数] 将完整文本转换为 SSE 流
 * @param {string} text - 要流式传输的完整文本
 * @param {string} requestId - 请求ID
 * @param {string} model - 模型名称
 * @returns {ReadableStream} - 一个 SSE 格式的可读流
 */
function streamTextAsSse(text, requestId, model) {
  const encoder = new TextEncoder();
  let position = 0;

  return new ReadableStream({
    async start(controller) {
      async function push() {
        if (position >= text.length) {
          // 发送终止信号
          const doneChunk = {
            id: requestId,
            object: "chat.completion.chunk",
            created: Math.floor(Date.now() / 1000),
            model: model,
            choices: [{ index: 0, delta: {}, finish_reason: "stop" }],
          };
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(doneChunk)}\n\n`));
          controller.enqueue(encoder.encode(`data: [DONE]\n\n`));
          controller.close();
          return;
        }

        // 随机决定本次发送的字符数，模拟真实打字效果
        const chunkSize = Math.floor(Math.random() * 3) + 1;
        const chunkContent = text.substring(position, position + chunkSize);
        position += chunkSize;

        const chunk = {
          id: requestId,
          object: "chat.completion.chunk",
          created: Math.floor(Date.now() / 1000),
          model: model,
          choices: [{ index: 0, delta: { content: chunkContent }, finish_reason: null }],
        };

        controller.enqueue(encoder.encode(`data: ${JSON.stringify(chunk)}\n\n`));
        
        // 等待一小段时间再发送下一个块
        setTimeout(push, CONFIG.PSEUDO_STREAM_CHUNK_DELAY);
      }
      await push();
    },
  });
}


// ====================================================================================
// 第二部分：前端UI (Developer Cockpit)
// ====================================================================================

/**
 * [UI处理器] 返回“开发者驾驶舱”的完整HTML页面
 * 采用【模式：原子化Worker应用】，将所有资产内联。
 * [修复] 此函数不依赖于请求对象，已移除未使用的 'request' 参数。
 */
function handleUIPage() {
  // [修复] 将整个HTML字符串改为使用模板字符串（反引号 ``），以便注入后端变量
  const html = `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>开发者驾驶舱 | ${CONFIG.PROJECT_NAME}</title>
    <style>
      /* --- 全局样式与主题 --- */
      :root {
        --bg-color: #121212;
        --surface-color: #1E1E1E;
        --primary-text-color: #E0E0E0;
        --secondary-text-color: #888888;
        --border-color: #333333;
        --highlight-color: #FFBF00; /* 琥珀色 */
        --error-color: #CF6679;
        --success-color: #66BB6A;
        --font-family-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
        --font-family-mono: 'SF Mono', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', monospace;
      }
      * { box-sizing: border-box; }
      html, body {
        margin: 0;
        padding: 0;
        background-color: var(--bg-color);
        color: var(--primary-text-color);
        font-family: var(--font-family-sans);
        font-size: 14px;
        line-height: 1.6;
      }
      main {
        display: grid;
        grid-template-columns: 380px 1fr;
        gap: 24px;
        padding: 24px;
        height: 100vh;
      }
      @media (max-width: 900px) {
        main {
          grid-template-columns: 1fr;
          height: auto;
        }
      }
      /* --- 骨架屏效果 --- */
      .skeleton {
        background-color: #2a2a2a;
        background-image: linear-gradient(90deg, #2a2a2a, #333333, #2a2a2a);
        background-size: 200% 100%;
        animation: skeleton-loading 1.5s infinite ease-in-out;
        border-radius: 4px;
      }
      @keyframes skeleton-loading {
        0% { background-position: 200% 0; }
        100% { background-position: -200% 0; }
      }
    </style>
</head>
<body>
    <main>
        <!-- 左栏：情报与指南 -->
        <aside>
            <info-panel></info-panel>
            <client-guides></client-guides>
        </aside>
        <!-- 右栏：实时终端 -->
        <section>
            <live-terminal></live-terminal>
        </section>
    </main>

    <script type="module">
    // ====================================================================================
    // 第三部分：客户端逻辑 (Client-Side Logic)
    // ====================================================================================

    // [修复] 将服务器端配置的关键值注入到客户端，供后续脚本使用
    const CONFIG = {
      API_MASTER_KEY: '${CONFIG.API_MASTER_KEY}',
      DEFAULT_MODEL: '${CONFIG.DEFAULT_MODEL}'
    };

    // --- 状态机与全局状态 ---
    const AppState = {
      INITIALIZING: 'INITIALIZING',
      HEALTH_CHECKING: 'HEALTH_CHECKING',
      READY: 'READY',
      REQUESTING: 'REQUESTING',
      STREAMING: 'STREAMING',
      ERROR: 'ERROR',
    };
    let currentState = AppState.INITIALIZING;
    let lastRequestStats = {};

    // --- SVG 图标库 ---
    const ICONS = {
      copy: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/><path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M3 1.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5M.5 10a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/></svg>',
      eye: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/><path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/></svg>',
      eyeSlash: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="m10.79 12.912-1.614-1.615a3.5 3.5 0 0 1-4.474-4.474l-2.06-2.06C.938 6.278 0 8 0 8s3 5.5 8 5.5a7.2 7.2 0 0 0 2.79-.588M5.21 3.088A7.3 7.3 0 0 1 8 3.5c5 0 8 5.5 8 5.5s-.939 1.721-2.641 3.238l-2.062-2.062a3.5 3.5 0 0 0-4.474-4.474z"/><path d="M5.525 7.646a2.5 2.5 0 0 0 2.829 2.829l-2.83-2.829zm4.95.708-2.829-2.83a2.5 2.5 0 0 1 2.829 2.829zm3.171 6-12-12 .708-.708 12 12z"/></svg>',
      send: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/></svg>',
      cancel: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/></svg>',
      check: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0"/></svg>',
      code: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M6.224 1.553a.5.5 0 0 1 .552 0l5 2.5a.5.5 0 0 1 0 .894l-5 2.5a.5.5 0 0 1-.552 0l-5-2.5a.5.5 0 0 1 0-.894zM2.13 6.333l5 2.5a.5.5 0 0 0 .552 0l5-2.5a.5.5 0 0 0 0-.894l-5-2.5a.5.5 0 0 0-.552 0l-5 2.5a.5.5 0 0 0 0 .894M1.68 9.21l5 2.5a.5.5 0 0 0 .552 0l5-2.5a.5.5 0 0 0 0-.894l-5-2.5a.5.5 0 0 0-.552 0l-5 2.5a.5.5 0 0 0 0 .894m5.369 3.236a.5.5 0 0 1 .552 0l5-2.5a.5.5 0 0 1 0-.894l-5-2.5a.5.5 0 0 1-.552 0l-5 2.5a.5.5 0 0 1 0 .894z"/></svg>',
      info: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/><path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/></svg>',
    };

    // --- 自定义元素 (Custom Elements) ---

    /**
     * <info-panel> 组件
     * 显示即用情报，如API地址、密钥等。
     */
    class InfoPanel extends HTMLElement {
      constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.render();
      }

      render(state = AppState.INITIALIZING) {
        const isLoading = state === AppState.INITIALIZING;
        const apiUrl = window.location.origin + '/v1/chat/completions';
        // 现在从客户端的CONFIG对象获取值
        const apiKey = CONFIG.API_MASTER_KEY;
        const defaultModel = CONFIG.DEFAULT_MODEL;

        this.shadowRoot.innerHTML = \`
          <style>
            :host { display: block; margin-bottom: 24px; }
            .panel { background-color: var(--surface-color); border: 1px solid var(--border-color); border-radius: 8px; padding: 20px; }
            h2 { margin: 0 0 16px; font-size: 1.2em; display: flex; align-items: center; gap: 8px; }
            .info-item { margin-bottom: 16px; }
            .info-item:last-child { margin-bottom: 0; }
            label { display: block; color: var(--secondary-text-color); font-size: 0.9em; margin-bottom: 6px; }
            .value-container { display: flex; align-items: center; background-color: var(--bg-color); border: 1px solid var(--border-color); border-radius: 4px; padding: 8px 12px; }
            .value { flex-grow: 1; font-family: var(--font-family-mono); color: var(--highlight-color); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
            .value.password { -webkit-text-security: disc; }
            .actions button { background: none; border: none; color: var(--secondary-text-color); cursor: pointer; padding: 4px; display: flex; align-items: center; }
            .actions button:hover { color: var(--primary-text-color); }
            .actions button svg { width: 16px; height: 16px; }
            .skeleton-text { height: 20px; width: 80%; margin-top: 4px; }
          </style>
          <div class="panel">
            <h2>\${ICONS.info} 即用情报</h2>
            <div class="info-item">
              <label>API 端点 (Endpoint)</label>
              <div class="value-container">
                \${isLoading ? '<div class="skeleton skeleton-text"></div>' : \`<div class="value" id="api-url">\${apiUrl}</div>\`}
                <div class="actions">
                  <button id="copy-url-btn" title="复制">\${ICONS.copy}</button>
                </div>
              </div>
            </div>
            <div class="info-item">
              <label>API 密钥 (Key)</label>
              <div class="value-container">
                \${isLoading ? '<div class="skeleton skeleton-text"></div>' : \`<div class="value password" id="api-key">\${apiKey}</div>\`}
                <div class="actions">
                  <button id="toggle-key-btn" title="显示/隐藏">\${ICONS.eyeSlash}</button>
                  <button id="copy-key-btn" title="复制">\${ICONS.copy}</button>
                </div>
              </div>
            </div>
            <div class="info-item">
              <label>默认模型 (Model)</label>
              <div class="value-container">
                \${isLoading ? '<div class="skeleton skeleton-text"></div>' : \`<div class="value">\${defaultModel}</div>\`}
              </div>
            </div>
          </div>
        \`;
        this.addEventListeners();
      }

      addEventListeners() {
        const copy = (id, value) => {
          const btn = this.shadowRoot.getElementById(id);
          if (btn) {
            btn.addEventListener('click', () => {
              navigator.clipboard.writeText(value);
              const originalIcon = btn.innerHTML;
              btn.innerHTML = ICONS.check;
              setTimeout(() => btn.innerHTML = originalIcon, 1500);
            });
          }
        };
        copy('copy-url-btn', window.location.origin + '/v1/chat/completions');
        copy('copy-key-btn', CONFIG.API_MASTER_KEY);

        const toggleBtn = this.shadowRoot.getElementById('toggle-key-btn');
        const keyEl = this.shadowRoot.getElementById('api-key');
        if (toggleBtn && keyEl) {
          toggleBtn.addEventListener('click', () => {
            const isPassword = keyEl.classList.toggle('password');
            toggleBtn.innerHTML = isPassword ? ICONS.eyeSlash : ICONS.eye;
          });
        }
      }
    }
    customElements.define('info-panel', InfoPanel);

    /**
     * <client-guides> 组件
     * 显示主流客户端的集成指南。
     */
    class ClientGuides extends HTMLElement {
        constructor() {
            super();
            this.attachShadow({ mode: 'open' });
            this.render();
        }

        render() {
            const apiUrl = window.location.origin + '/v1';
            const apiKey = CONFIG.API_MASTER_KEY;
            const model = CONFIG.DEFAULT_MODEL;

            this.shadowRoot.innerHTML = \`
                <style>
                    :host { display: block; }
                    details { background-color: var(--surface-color); border: 1px solid var(--border-color); border-radius: 8px; margin-bottom: 24px; }
                    summary { padding: 16px; cursor: pointer; font-weight: 500; display: flex; align-items: center; gap: 8px; }
                    summary::-webkit-details-marker { display: none; }
                    summary:before { content: '▶'; font-size: 0.8em; margin-right: 8px; transition: transform 0.2s; }
                    details[open] > summary:before { transform: rotate(90deg); }
                    .content { padding: 0 16px 16px; border-top: 1px solid var(--border-color); }
                    .tabs { display: flex; border-bottom: 1px solid var(--border-color); margin-bottom: 16px; }
                    .tab { padding: 8px 16px; cursor: pointer; color: var(--secondary-text-color); }
                    .tab.active { color: var(--highlight-color); border-bottom: 2px solid var(--highlight-color); }
                    .tab-content { display: none; }
                    .tab-content.active { display: block; }
                    pre { background-color: var(--bg-color); padding: 16px; border-radius: 4px; font-family: var(--font-family-mono); white-space: pre-wrap; word-break: break-all; font-size: 0.9em; position: relative; }
                    .copy-code-btn { position: absolute; top: 8px; right: 8px; background: var(--surface-color); border: 1px solid var(--border-color); color: var(--secondary-text-color); cursor: pointer; border-radius: 4px; padding: 4px 8px; }
                    .copy-code-btn:hover { color: var(--primary-text-color); }
                </style>
                <details>
                    <summary>\${ICONS.code} 主流客户端集成指南</summary>
                    <div class="content">
                        <div class="tabs">
                            <div class="tab active" data-tab="nextweb">ChatGPT-Next-Web</div>
                            <div class="tab" data-tab="lobe">LobeChat</div>
                            <div class="tab" data-tab="curl">cURL</div>
                            <div class="tab" data-tab="python">Python</div>
                        </div>
                        <div id="nextweb" class="tab-content active">
                            <p>在设置页面，填入以下信息：</p>
                            <pre><code>接口地址: \${apiUrl}</code><button class="copy-code-btn">复制</button></pre>
                            <pre><code>API Key: \${apiKey}</code><button class="copy-code-btn">复制</button></pre>
                            <pre><code>自定义模型: \${model}</code><button class="copy-code-btn">复制</button></pre>
                        </div>
                        <div id="lobe" class="tab-content">
                            <p>在设置 -> 语言模型 -> OpenAI，填入以下信息：</p>
                            <pre><code>API Key: \${apiKey}</code><button class="copy-code-btn">复制</button></pre>
                            <pre><code>API 地址: \${apiUrl}</code><button class="copy-code-btn">复制</button></pre>
                            <p>然后即可在模型列表中找到 <code>\${model}</code>。</p>
                        </div>
                        <div id="curl" class="tab-content">
                            <pre><code id="curl-code">curl -X POST \${apiUrl}/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \${apiKey}" \\
  -d '{
    "model": "\${model}",
    "messages": [
      {
        "role": "user",
        "content": "你好"
      }
    ],
    "stream": true
  }'</code><button class="copy-code-btn">复制</button></pre>
                        </div>
                        <div id="python" class="tab-content">
                            <pre><code id="python-code">import openai

client = openai.OpenAI(
    api_key="\${apiKey}",
    base_url="\${apiUrl}"
)

stream = client.chat.completions.create(
    model="\${model}",
    messages=[{"role": "user", "content": "你好"}],
    stream=True,
)

for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")
</code><button class="copy-code-btn">复制</button></pre>
                        </div>
                    </div>
                </details>
            \`;
            this.addEventListeners();
        }

        addEventListeners() {
            const tabs = this.shadowRoot.querySelectorAll('.tab');
            const tabContents = this.shadowRoot.querySelectorAll('.tab-content');
            tabs.forEach(tab => {
                tab.addEventListener('click', () => {
                    tabs.forEach(t => t.classList.remove('active'));
                    tab.classList.add('active');
                    tabContents.forEach(c => c.classList.remove('active'));
                    this.shadowRoot.getElementById(tab.dataset.tab).classList.add('active');
                });
            });

            this.shadowRoot.querySelectorAll('.copy-code-btn').forEach(btn => {
                btn.addEventListener('click', () => {
                    const code = btn.previousElementSibling.textContent;
                    navigator.clipboard.writeText(code);
                    btn.textContent = '已复制!';
                    setTimeout(() => btn.textContent = '复制', 1500);
                });
            });
        }
    }
    customElements.define('client-guides', ClientGuides);

    /**
     * <live-terminal> 组件
     * 实时交互终端，包含状态指示、输出、输入和日志。
     */
    class LiveTerminal extends HTMLElement {
      constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.abortController = null;
        this.render();
      }

      render(state = AppState.INITIALIZING, data = {}) {
        currentState = state;
        this.shadowRoot.innerHTML = \`
          <style>
            :host { display: flex; flex-direction: column; height: 100%; }
            .terminal { display: flex; flex-direction: column; height: 100%; background-color: var(--surface-color); border: 1px solid var(--border-color); border-radius: 8px; overflow: hidden; }
            .header { display: flex; justify-content: space-between; align-items: center; padding: 12px 20px; border-bottom: 1px solid var(--border-color); flex-shrink: 0; }
            h2 { margin: 0; font-size: 1.2em; }
            .status-indicator { display: flex; align-items: center; gap: 8px; font-size: 0.9em; }
            .status-dot { width: 10px; height: 10px; border-radius: 50%; }
            .status-dot.initializing { background-color: var(--secondary-text-color); animation: pulse 1.5s infinite; }
            .status-dot.ready { background-color: var(--success-color); }
            .status-dot.requesting { background-color: var(--highlight-color); animation: pulse 1.5s infinite; }
            .status-dot.error { background-color: var(--error-color); }
            @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
            .output-container { flex-grow: 1; padding: 20px; overflow-y: auto; font-family: var(--font-family-sans); line-height: 1.7; }
            .output-container .skeleton { height: 20px; margin-bottom: 12px; }
            .output-container .skeleton:last-child { width: 60%; }
            .output-container .message { margin-bottom: 1em; }
            .output-container .message.user { color: var(--secondary-text-color); }
            .output-container .message.assistant p { margin: 0; }
            .output-container .message.assistant pre { background-color: var(--bg-color); padding: 1em; border-radius: 4px; white-space: pre-wrap; }
            .output-container .message.assistant code { font-family: var(--font-family-mono); }
            .output-container .message.error { color: var(--error-color); }
            .input-area { border-top: 1px solid var(--border-color); padding: 16px; display: flex; align-items: flex-end; gap: 12px; flex-shrink: 0; }
            textarea { flex-grow: 1; background-color: var(--bg-color); border: 1px solid var(--border-color); border-radius: 4px; padding: 10px; color: var(--primary-text-color); font-family: var(--font-family-sans); resize: none; font-size: 1em; max-height: 200px; }
            textarea:focus { outline: none; border-color: var(--highlight-color); }
            .send-btn { background-color: var(--highlight-color); color: var(--bg-color); border: none; border-radius: 50%; width: 40px; height: 40px; flex-shrink: 0; cursor: pointer; display: flex; align-items: center; justify-content: center; }
            .send-btn:disabled { background-color: var(--border-color); cursor: not-allowed; }
            .send-btn svg { width: 18px; height: 18px; }
          </style>
          <div class="terminal">
            <div class="header">
              <h2>实时交互终端</h2>
              <div class="status-indicator">
                <div id="status-dot" class="status-dot initializing"></div>
                <span id="status-text">初始化中...</span>
              </div>
            </div>
            <div id="output" class="output-container">
              <div class="skeleton"></div>
              <div class="skeleton"></div>
              <div class="skeleton"></div>
            </div>
            <div class="input-area">
              <textarea id="prompt-input" rows="1" placeholder="输入你的指令..."></textarea>
              <button id="send-btn" class="send-btn" disabled>\${ICONS.send}</button>
            </div>
          </div>
        \`;
        this.updateState(state, data);
        this.addEventListeners();
      }

      addEventListeners() {
        const promptInput = this.shadowRoot.getElementById('prompt-input');
        const sendBtn = this.shadowRoot.getElementById('send-btn');

        promptInput.addEventListener('input', () => {
          promptInput.style.height = 'auto';
          promptInput.style.height = (promptInput.scrollHeight) + 'px';
          sendBtn.disabled = promptInput.value.trim() === '' || (currentState !== AppState.READY && currentState !== AppState.ERROR);
        });

        promptInput.addEventListener('keydown', (e) => {
          if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            if (!sendBtn.disabled) sendBtn.click();
          }
        });

        sendBtn.addEventListener('click', () => {
          if (currentState === AppState.REQUESTING || currentState === AppState.STREAMING) {
            this.abortController?.abort();
            this.updateState(AppState.READY, { message: "用户已取消请求。" });
          } else {
            const prompt = promptInput.value.trim();
            if (prompt) {
              this.sendMessage(prompt);
              promptInput.value = '';
              promptInput.style.height = 'auto';
            }
          }
        });
      }

      updateState(newState, data = {}) {
        currentState = newState;
        const statusDot = this.shadowRoot.getElementById('status-dot');
        const statusText = this.shadowRoot.getElementById('status-text');
        const sendBtn = this.shadowRoot.getElementById('send-btn');
        const promptInput = this.shadowRoot.getElementById('prompt-input');
        const output = this.shadowRoot.getElementById('output');

        switch (newState) {
          case AppState.INITIALIZING:
            statusDot.className = 'status-dot initializing';
            statusText.textContent = '初始化中...';
            sendBtn.disabled = true;
            promptInput.disabled = true;
            break;
          case AppState.HEALTH_CHECKING:
            statusDot.className = 'status-dot initializing';
            statusText.textContent = '上游健康检查...';
            sendBtn.disabled = true;
            promptInput.disabled = true;
            output.innerHTML = ''; // 清空骨架屏
            break;
          case AppState.READY:
            statusDot.className = 'status-dot ready';
            statusText.textContent = '服务就绪';
            sendBtn.innerHTML = ICONS.send;
            sendBtn.disabled = promptInput.value.trim() === '';
            promptInput.disabled = false;
            if (data.message) {
                this.appendMessage('assistant', data.message);
            }
            break;
          case AppState.REQUESTING:
            statusDot.className = 'status-dot requesting';
            statusText.textContent = '请求中...';
            sendBtn.innerHTML = ICONS.cancel;
            sendBtn.disabled = false;
            promptInput.disabled = true;
            this.appendMessage('user', data.prompt);
            this.appendMessage('assistant', '', true); // 准备一个空的助手消息容器
            break;
          case AppState.STREAMING:
            statusDot.className = 'status-dot requesting';
            statusText.textContent = '流式响应中...';
            this.updateLastMessage(data.chunk);
            break;
          case AppState.ERROR:
            statusDot.className = 'status-dot error';
            statusText.textContent = '发生错误';
            sendBtn.innerHTML = ICONS.send;
            sendBtn.disabled = promptInput.value.trim() === '';
            promptInput.disabled = false;
            this.appendMessage('error', \`错误: \${data.error}\`);
            break;
        }
      }
      
      appendMessage(role, content, isStreaming = false) {
        const output = this.shadowRoot.getElementById('output');
        const messageEl = document.createElement('div');
        messageEl.className = \`message \${role}\`;
        if (isStreaming) {
            messageEl.id = 'streaming-message';
        }
        messageEl.innerHTML = \`<p>\${content}</p>\`;
        output.appendChild(messageEl);
        output.scrollTop = output.scrollHeight;
      }

      updateLastMessage(chunk) {
        const streamingMessage = this.shadowRoot.getElementById('streaming-message');
        if (streamingMessage) {
            // 简单实现，不使用Markdown库以保持轻量
            streamingMessage.querySelector('p').textContent += chunk;
            streamingMessage.parentElement.scrollTop = streamingMessage.parentElement.scrollHeight;
        }
      }

      async sendMessage(prompt) {
        this.abortController = new AbortController();
        this.updateState(AppState.REQUESTING, { prompt });

        try {
          const response = await fetch('/v1/chat/completions', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              // 现在可以安全地从客户端的CONFIG对象获取值
              'Authorization': \`Bearer \${CONFIG.API_MASTER_KEY}\`,
            },
            body: JSON.stringify({
              // 现在可以安全地从客户端的CONFIG对象获取值
              model: CONFIG.DEFAULT_MODEL,
              messages: [{ role: 'user', content: prompt }],
              stream: true,
            }),
            signal: this.abortController.signal,
          });

          if (!response.ok) {
            const errorData = await response.json();
            throw new Error(errorData.error.message || 'API 请求失败');
          }

          const reader = response.body.pipeThrough(new TextDecoderStream()).getReader();
          
          while (true) {
            const { value, done } = await reader.read();
            if (done) {
              this.updateState(AppState.READY);
              break;
            }
            
            const lines = value.split('\\n').filter(line => line.startsWith('data: '));
            for (const line of lines) {
              const jsonStr = line.substring(6);
              if (jsonStr === '[DONE]') {
                this.updateState(AppState.READY);
                return;
              }
              try {
                const data = JSON.parse(jsonStr);
                const content = data.choices[0]?.delta?.content;
                if (content) {
                  this.updateState(AppState.STREAMING, { chunk: content });
                }
              } catch (e) {
                // 忽略解析错误
              }
            }
          }
        } catch (err) {
          if (err.name === 'AbortError') {
            // 已经在点击取消时处理
          } else {
            this.updateState(AppState.ERROR, { error: err.message });
          }
        }
      }
    }
    customElements.define('live-terminal', LiveTerminal);

    // --- 应用初始化 ---
    document.addEventListener('DOMContentLoaded', () => {
      const infoPanel = document.querySelector('info-panel');
      const liveTerminal = document.querySelector('live-terminal');

      // 模拟初始化和健康检查流程
      setTimeout(() => {
        infoPanel.render(AppState.HEALTH_CHECKING);
        liveTerminal.updateState(AppState.HEALTH_CHECKING);
        // 模拟健康检查成功
        setTimeout(() => {
          infoPanel.render(AppState.READY);
          liveTerminal.updateState(AppState.READY, { message: "欢迎使用开发者驾驶舱。请输入指令开始交互。" });
        }, 1000);
      }, 500);
    });

    </script>
</body>
</html>
  `;
  // 注意：Cloudflare Worker 会自动处理压缩，此处无需手动设置 Content-Encoding
  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    }
  });
}
